"""Implementation of fastgit

Docs: https://AnswerDotAI.github.io/fastgit/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['GitRes', 'callgit', 'get_top', 'Git', 'acallgit']

# %% ../nbs/00_core.ipynb #c63a3ea7
from fastcore.utils import *
from fastcore.aio import then
import subprocess,asyncio
from subprocess import CalledProcessError

# %% ../nbs/00_core.ipynb #880c6a46
_ok1 = {'merge-tree','merge-base','grep','check-ignore','diff','diff-index','diff-files','diff-tree','show-ref','config','rev-parse'}

class GitRes(str):
    "Git output `str`, carrying the command's `returncode`"
    def __new__(cls, s, returncode=0):
        self = super().__new__(cls, s)
        self.returncode = returncode
        return self

# %% ../nbs/00_core.ipynb #e4c0a290
def _gitcmd(path, *args, pre=None):
    cmd = ['git', '-C', str(Path(path).expanduser().resolve())] + list(args)
    return [*pre, *cmd] if pre else cmd

def _depr_uname(uname, pre):
    assert not (uname and pre), "Pass `uname` or `pre`, not both"
    if not uname: return pre
    warn("`uname` is deprecated; pass e.g `pre=['/usr/bin/sudo','-u',uname]` instead", DeprecationWarning, stacklevel=4)
    return ['/usr/bin/sudo', '-u', uname]

def _gitres(args, out, err, returncode, ok_exit):
    if ok_exit is None: ok_exit = 1 if args and args[0] in _ok1 else 0
    if returncode not in (0, *listify(ok_exit)): raise CalledProcessError(returncode, ['git', *args], out, err)
    return GitRes((out + err).strip(), returncode)

def _runlocal(path, args, pre=None):
    "Default runner: compose the local argv and run it in a subprocess"
    r = subprocess.run(_gitcmd(path, *args, pre=pre), capture_output=True, text=True)
    return r.stdout, r.stderr, r.returncode

def callgit(
    path, # Directory to run git in
    *args, # git subcommand and arguments
    uname=None, # Deprecated; use `pre`
    pre=None, # argv prefix, e.g. a sudo wrapper
    ok_exit=None, # Extra accepted exit codes (default: 1 for `_ok1` commands)
    runner=None, # Replaces the local subprocess: `(path, args, pre) -> (stdout, stderr, returncode)`
):
    "Run git in `path`, returning stripped stdout+stderr as a `GitRes`"
    out,err,rc = (runner or _runlocal)(path, list(args), pre=_depr_uname(uname, pre))
    return _gitres(args, out, err, rc, ok_exit)

# %% ../nbs/00_core.ipynb #4c0df6c6
def get_top(folder, runner=None):
    try: return callgit(folder, 'rev-parse', '--show-toplevel', runner=runner)
    except CalledProcessError: return None

# %% ../nbs/00_core.ipynb #97f78839
class Git:
    "Run git commands in dir `d`; `sync=False` makes every command return an awaitable"
    def __init__(self, d, pre=None, raise_exc=False, sync=True, runner=None): self.d,self.pre,self.raise_exc,self._sync,self.runner = Path(d).expanduser(),pre,raise_exc,sync,runner

    def __call__(self, cmd, *args, mute_errors=False, raise_exc=None, ok_exit=None, **kwargs):
        paths = [str(p) for p in listify(kwargs.pop('__', None) or [])]
        args = listify(args)
        kwargs = {k:v for k,v in kwargs.items() if v is not False}
        args += concat((f'-{k}',str(v)) for k,v in kwargs.items() if len(k)==1 and v is not True)
        args += [f'-{k}' for k,v in kwargs.items() if len(k)==1 and v is True]
        args += [f'--{k.replace("_","-")}={v}' for k,v in kwargs.items() if len(k)>1 and v is not True]
        args += [f'--{k.replace("_","-")}' for k,v in kwargs.items() if len(k)>1 and v is True]
        if paths: args += ['--'] + paths
        f = self._run if self._sync else self._arun
        return f(cmd, args, mute_errors, ifnone(raise_exc, self.raise_exc), ok_exit)

    def _run(self, cmd, args, mute_errors, raise_exc, ok_exit):
        try: return callgit(self.d, cmd, *args, pre=self.pre, ok_exit=ok_exit, runner=self.runner)
        except CalledProcessError as e: self._err(e, cmd, args, mute_errors, raise_exc)

    async def _arun(self, cmd, args, mute_errors, raise_exc, ok_exit):
        try: return await acallgit(self.d, cmd, *args, pre=self.pre, ok_exit=ok_exit, runner=self.runner)
        except CalledProcessError as e: self._err(e, cmd, args, mute_errors, raise_exc)

    def _err(self, e, cmd, args, mute_errors, raise_exc):
        if raise_exc: raise e
        if not mute_errors: print(f"ERROR: git {' '.join(map(str, [cmd, *args]))}: {e.stderr.strip()}")

    def __getattr__(self, nm):
        if nm.startswith('_'): raise AttributeError(nm)
        return partial(self, nm.replace('_','-'))

    def top(self): return self.rev_parse('--show-toplevel', mute_errors=True, raise_exc=False)

    @property
    def exists(self): return then(self.top(), lambda r: r is not None)
    @property
    def head_sha(self): return self.rev_parse('HEAD', mute_errors=True, raise_exc=False)

# %% ../nbs/00_core.ipynb #b688e74b
@patch(as_prop=True)
def last_commit(self:Git): return self.log('-1', pretty='format:%s')

# %% ../nbs/00_core.ipynb #fdf315b8
@patch(as_prop=True)
def commits(self:Git): return then(self.log('--oneline', mute_errors=True, raise_exc=False), lambda r: (r or '').splitlines())

# %% ../nbs/00_core.ipynb #712ca55b
@patch(as_prop=True)
def current_branch(self:Git): return self.branch('--show-current')

# %% ../nbs/00_core.ipynb #b69ecf1c
async def _arunlocal(path, args, pre=None):
    "Async `_runlocal`"
    cmd = _gitcmd(path, *args, pre=pre)
    p = await asyncio.create_subprocess_exec(*cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out,err = await p.communicate()
    return out.decode(), err.decode(), p.returncode

async def acallgit(
    path, # Directory to run git in
    *args, # git subcommand and arguments
    uname=None, # Deprecated; use `pre`
    pre=None, # argv prefix, e.g. a sudo wrapper
    ok_exit=None, # Extra accepted exit codes (default: 1 for `_ok1` commands)
    runner=None, # Async runner replacing the local subprocess: `async (path, args, pre) -> (stdout, stderr, returncode)`
):
    "Async `callgit`: identical contract, run in an `asyncio` subprocess"
    out,err,rc = await (runner or _arunlocal)(path, list(args), pre=_depr_uname(uname, pre))
    return _gitres(args, out, err, rc, ok_exit)
