"""Implementation of fastgit

Docs: https://AnswerDotAI.github.io/fastgit/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['callgit', 'get_top', 'Git']

# %% ../nbs/00_core.ipynb #c63a3ea7
from fastcore.utils import *
import subprocess
from subprocess import CalledProcessError

# %% ../nbs/00_core.ipynb #e4c0a290
def callgit(path, *args, uname=None, pre=None):
    "Run git in `path`, non-interactively (editors suppressed), returning stripped stdout+stderr as a single `str`"
    assert not (uname and pre), "Pass `uname` or `pre`, not both"
    if uname:
        warn("`uname` is deprecated; pass e.g `pre=['/usr/bin/sudo','-u',uname]` instead", DeprecationWarning, stacklevel=2)
        pre = ['/usr/bin/sudo', '-u', uname]
    fp = Path(path).expanduser().resolve()
    args = ['git', '-C', str(fp)] + list(args)
    if pre: args = [*pre, *args]
    r = subprocess.run(args, capture_output=True, text=True, check=True,
                       env=os.environ|dict(GIT_EDITOR='true', GIT_SEQUENCE_EDITOR='true'))
    return (r.stdout + r.stderr).strip()

# %% ../nbs/00_core.ipynb #4c0df6c6
def get_top(folder):
    try: return callgit(folder, 'rev-parse', '--show-toplevel')
    except CalledProcessError: return None

# %% ../nbs/00_core.ipynb #97f78839
class Git:
    "Run git commands in dir `d`"
    def __init__(self, d, pre=None, raise_exc=False): self.d,self.pre,self.raise_exc = Path(d).expanduser(),pre,raise_exc

    def __call__(self, cmd, *args, mute_errors=False, raise_exc=None, **kwargs):
        paths = [str(p) for p in listify(kwargs.pop('__', None) or [])]
        args = listify(args)
        kwargs = {k:v for k,v in kwargs.items() if v is not False}
        args += concat((f'-{k}',str(v)) for k,v in kwargs.items() if len(k)==1 and v is not True)
        args += [f'-{k}' for k,v in kwargs.items() if len(k)==1 and v is True]
        args += [f'--{k.replace("_","-")}={v}' for k,v in kwargs.items() if len(k)>1 and v is not True]
        args += [f'--{k.replace("_","-")}' for k,v in kwargs.items() if len(k)>1 and v is True]
        if paths: args += ['--'] + paths
        try: return callgit(self.d, cmd, *args, pre=self.pre)
        except CalledProcessError as e:
            if ifnone(raise_exc, self.raise_exc): raise
            if not mute_errors: print(f"ERROR: git {' '.join(map(str, [cmd, *args]))}: {e.stderr.strip()}")

    def __getattr__(self, nm):
        if nm.startswith('_'): raise AttributeError(nm)
        return partial(self, nm.replace('_','-'))

    def top(self): return self.rev_parse('--show-toplevel', mute_errors=True, raise_exc=False)

    @property
    def exists(self): return self.top() is not None
    @property
    def head_sha(self): return self.rev_parse('HEAD', mute_errors=True, raise_exc=False)

# %% ../nbs/00_core.ipynb #b688e74b
@patch(as_prop=True)
def last_commit(self:Git): return self.log('-1', pretty='format:%s')

# %% ../nbs/00_core.ipynb #fdf315b8
@patch(as_prop=True)
def commits(self:Git): return (self.log('--oneline', mute_errors=True, raise_exc=False) or '').splitlines()

# %% ../nbs/00_core.ipynb #712ca55b
@patch(as_prop=True)
def current_branch(self:Git): return self.branch('--show-current')
