"""Commits, refs, diffs, and status as live Python objects

Docs: https://AnswerDotAI.github.io/fastgit/repo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_repo.ipynb.

# %% auto #0
__all__ = ['Repo', 'GitObj', 'Commit', 'Commits', 'Ref', 'Refs', 'DiffFile', 'Diff', 'StatusEntry', 'Status', 'BlameLine',
           'Blame', 'Remote', 'Remotes', 'Stash', 'Stashes']

# %% ../nbs/01_repo.ipynb #7c57fcf7
from fastcore.utils import *
from .core import *
import re, subprocess
from datetime import datetime, timezone, timedelta

# %% ../nbs/01_repo.ipynb #aabe4562
class Repo(Git):
    "A `Git` handle whose common queries return live objects instead of strings"

# %% ../nbs/01_repo.ipynb #17251ab6
_commit_f = dict(sha='%H', short='%h', parents='%P', author='%an', email='%ae', date='%aI', msg='%s')

def _fmt(fields): return '%x1f'.join(fields.values())+'%x1e'

def _conv(k, v):
    if k=='parents': return v.split()
    if k=='date': return datetime.fromisoformat(v)
    return v

def _parse(fields, s):
    "Parse `%x1f`/`%x1e`-delimited output into one dict per record"
    return [{k:_conv(k,v) for k,v in zip(fields, rec.strip('\n').split('\x1f'))}
        for rec in (s or '').split('\x1e') if rec.strip()]

# %% ../nbs/01_repo.ipynb #95961923
class GitObj(AttrDict):
    "Base for git handles: plain-text display, shown via `__repr__`"
    def _repr_markdown_(self): return None
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

class Commit(GitObj):
    "A git commit: immutable, addressed by `sha`"
    def __repr__(self): return f'{self.short} {self.msg}'

class Commits(L):
    "Commits shown as a `--oneline`-style log"
    def __repr__(self): return '\n'.join(repr(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

# %% ../nbs/01_repo.ipynb #6f3d7fdb
@patch
def log(self:Repo, *args, **kwargs):
    "`Commits` for `git log` `args`: revision ranges ('main..feat'), flags, paths via `__`"
    res = self('log', *args, format=_fmt(_commit_f), mute_errors=True, **kwargs)
    return Commits(Commit(d, _g=self) for d in _parse(_commit_f, res))

@patch
def at(self:Repo, rev):
    "The `Commit` for commit-ish `rev` (sha, ref name, 'HEAD~2', `Ref`, ...); None if unknown"
    return first(self.log(str(getattr(rev, 'sha', rev)), n=1))

@patch(as_prop=True)
def head(self:Repo):
    "The `Commit` at HEAD"
    return self.at('HEAD')

@patch(as_prop=True)
def parent(self:Commit):
    "First-parent `Commit`, or None for a root commit"
    return self._g.at(self.parents[0]) if self.parents else None

# %% ../nbs/01_repo.ipynb #e017095b
_ref_f = dict(name='%(refname:short)', sha='%(objectname)', upstream='%(upstream:short)',
    track='%(upstream:track)', cur='%(HEAD)', msg='%(subject)')

class Ref(GitObj):
    "A git ref: a mutable named pointer to a commit"
    def __repr__(self):
        up = f" [{self.upstream}{': '+self.track.strip('[]') if self.track else ''}]" if self.upstream else ''
        return f"{'*' if self.cur=='*' else ' '} {self.name} {self.sha[:7]}{up} {self.msg}"
    @property
    def ahead(self): return int(m.group(1)) if (m:=re.search(r'ahead (\d+)', self.track)) else 0
    @property
    def behind(self): return int(m.group(1)) if (m:=re.search(r'behind (\d+)', self.track)) else 0
    @property
    def commit(self): return self._g.at(self.sha)

class Refs(L):
    "Refs shown as `branch -vv`-style lines"
    def __repr__(self): return '\n'.join(repr(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

# %% ../nbs/01_repo.ipynb #ba48317b
@patch
def _refs(self:Repo, pat):
    res = self('for-each-ref', pat, format='%1f'.join(_ref_f.values())+'%1e', mute_errors=True)
    return Refs(Ref(d, _g=self) for d in _parse(_ref_f, res))

@patch(as_prop=True)
def branches(self:Repo):
    "Local branches as `Refs`"
    return self._refs('refs/heads')

@patch(as_prop=True)
def tags(self:Repo):
    "Tags as `Refs`"
    return self._refs('refs/tags')

# %% ../nbs/01_repo.ipynb #528e494d
class DiffFile(GitObj):
    "One changed file; `adds`/`dels` are None for binary files"
    def __repr__(self): return f"{self.path} | " + ('bin' if self.adds is None else f'+{self.adds} -{self.dels}')

class Diff(L):
    "Changed files shown `--stat`-style; the full patch text is in `.patch`"
    def __repr__(self):
        tot = f"{len(self)} files changed, +{sum(o.adds or 0 for o in self)} -{sum(o.dels or 0 for o in self)}"
        return '\n'.join([repr(o) for o in self] + [tot])
    def _repr_pretty_(self, p, cycle): p.text(repr(self))
    @property
    def patch(self):
        "Full patch text, as `git diff` prints it"
        return self._g('diff', *self._args, **self._kw)

# %% ../nbs/01_repo.ipynb #0c507c03
@patch
def diff(self:Repo, *args, **kwargs):
    "`Diff` for `git diff` `args`: commits, ranges ('a...b'), paths via `__`"
    res = self('diff', '--numstat', *args, mute_errors=True, **kwargs)
    def _row(ln):
        a,d,p = ln.split('\t', 2)
        return DiffFile(path=p, adds=None if a=='-' else int(a), dels=None if d=='-' else int(d))
    df = Diff(_row(o) for o in (res or '').splitlines())
    df._g,df._args,df._kw = self,args,kwargs
    return df

@patch
def __sub__(self:Commit, other):
    "`b - a` is the patch taking `a` to `b`, i.e. `git diff a b`"
    return self._g.diff(getattr(other, 'sha', str(other)), self.sha)

@patch
def __sub__(self:Ref, other): return self.commit - other

# %% ../nbs/01_repo.ipynb #a2496168
class StatusEntry(GitObj):
    "One changed path; `xy` is the porcelain staged/unstaged code pair"
    def __repr__(self): return f'{self.xy} {self.path}'


def _st_entry(ln):
    t,rest = ln[0],ln[2:]
    if t in '?!': return StatusEntry(xy=t*2, path=rest)
    p = rest.split(' ')
    if t=='1': return StatusEntry(xy=p[0], path=' '.join(p[7:]))
    if t=='2':
        path,orig = ' '.join(p[8:]).split('\t')
        return StatusEntry(xy=p[0], path=path, orig=orig)
    if t=='u': return StatusEntry(xy=p[0], path=' '.join(p[9:]), stages=p[6:9])

class Status(L):
    "Working-tree state shown `status -sb`-style: branch line, entries, in-progress op"
    branch=upstream=oid=op=None
    ahead=behind = 0
    def __repr__(self):
        ab = f' [ahead {self.ahead}, behind {self.behind}]' if self.ahead or self.behind else ''
        up = f'...{self.upstream}' if self.upstream else ''
        res = [f'## {self.branch}{up}{ab}'] + [repr(o) for o in self]
        if self.op: res.append(f'# {self.op} in progress')
        return '\n'.join(res)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))
    @property
    def clean(self): return not len(self)
    @property
    def conflicts(self):
        "Unmerged entries only"
        return L(o for o in self if o.xy=='UU')

# %% ../nbs/01_repo.ipynb #c04a8dfd
_op_f = dict(MERGE_HEAD='merge', CHERRY_PICK_HEAD='cherry-pick', REVERT_HEAD='revert', BISECT_LOG='bisect')

@patch(as_prop=True)
def status(self:Repo):
    "Current `Status`: branch info, changed/untracked/unmerged entries, any in-progress op"
    info,st = {},Status()
    for ln in (self('status', '--porcelain=v2', '--branch', mute_errors=True) or '').splitlines():
        if ln.startswith('# branch.'):
            k,_,v = ln[9:].partition(' ')
            info[k] = v
        elif ln: st.append(_st_entry(ln))
    st.branch,st.upstream,st.oid = info.get('head'),info.get('upstream'),info.get('oid')
    ab = re.findall(r'\d+', info.get('ab', ''))
    st.ahead,st.behind = map(int, ab) if ab else (0, 0)
    gd = Path(self('rev-parse', '--git-dir', mute_errors=True) or '.git')
    if not gd.is_absolute(): gd = self.d/gd
    st.op = first(v for k,v in _op_f.items() if (gd/k).exists())
    rb = first(p for o in ('rebase-merge','rebase-apply') if (p:=gd/o).exists())
    if not st.op and rb:
        nm = (rb/'head-name').read_text().strip().removeprefix('refs/heads/') if (rb/'head-name').exists() else ''
        st.op = f'rebase of {nm}' if nm else 'rebase'
    return st

# %% ../nbs/01_repo.ipynb #e3c633c9
@patch
def commit(self:Repo, msg=None, *args, **kwargs):
    "Commit staged changes, returning the new head `Commit`"
    if msg: kwargs['m'] = msg
    self('commit', *args, **kwargs)
    return self.head

@patch
def merge(self:Repo, *args, **kwargs):
    "Merge, returning the resulting `Status`: a conflict is a state, not an error"
    self('merge', *args, mute_errors=True, **kwargs)
    return self.status

@patch
def rebase(self:Repo, *args, **kwargs):
    "Rebase, returning the resulting `Status`"
    self('rebase', *args, mute_errors=True, **kwargs)
    return self.status

@patch
def pull(self:Repo, *args, **kwargs):
    "Pull, returning the resulting `Status`"
    self('pull', *args, mute_errors=True, **kwargs)
    return self.status

# %% ../nbs/01_repo.ipynb #11cf4693
@patch
def cat(self:Repo, spec):
    "Exact file content at `spec` ('rev:path', or ':1:'/':2:'/':3:' + path for conflict stages); no stripping, unlike raw verbs"
    args = [*(self.pre or []), 'git', '-C', str(self.d), 'show', str(spec)]
    return subprocess.run(args, capture_output=True, text=True, check=True).stdout

# %% ../nbs/01_repo.ipynb #48fa0ed1
def _lbound(o):
    "One `-L` range bound: an int line number, a `+N`/`-N` offset str, or a /pattern/"
    if isinstance(o, int): return str(o)
    if re.fullmatch(r'[+-]\d+', o): return o
    return '/'+o.replace('/', r'\/')+'/'

def _lspec(func=None, lines=None, regex=None):
    "A `git -L` range spec from whichever of `func`, `lines`, or `regex` is given"
    if func: return f':{func}'
    if lines: return f'{lines[0]},{lines[1]}'
    if regex:
        if isinstance(regex, str): regex = (regex, '+1')  # bare pattern: just the matched line
        return ','.join(_lbound(o) for o in regex)

def _tz(s): return timezone(timedelta(minutes=(-1 if s[0]=='-' else 1)*(int(s[1:3])*60+int(s[3:5]))))

class BlameLine(GitObj):
    "One blamed line; `sha`/`author`/`date`/`msg` describe the last commit to touch it"
    def __repr__(self): return f'{self.sha[:7]} ({self.author} {self.date:%Y-%m-%d %H:%M} {self.lineno:>3}) {self.line}'
    @property
    def commit(self): return self._g.at(self.sha)

class Blame(L):
    "Blame lines shown as `git blame` shows them"
    def __repr__(self): return '\n'.join(repr(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

@patch
def blame(self:Repo, path, *args, func=None, lines=None, regex=None):
    "`Blame` for `path` (`args` may add a revision or flags); `func`/`lines`/`regex` pick a `-L` range"
    spec = _lspec(func, lines, regex)
    cmd = [*(self.pre or []), 'git', '-C', str(self.d), 'blame', '--line-porcelain',
        *(['-L', spec] if spec else []), *args, '--', str(path)]
    cur,res = {},Blame()
    for ln in subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.splitlines():
        if ln.startswith('\t'): res.append(BlameLine(cur, line=ln[1:], _g=self))
        else:
            k,_,v = ln.partition(' ')
            if re.fullmatch(r'[0-9a-f]{40}', k): cur = dict(sha=k, lineno=int(v.split()[1]))
            elif k=='author': cur['author'] = v
            elif k=='author-time': cur['ts'] = int(v)
            elif k=='author-tz': cur['date'] = datetime.fromtimestamp(cur.pop('ts'), _tz(v))
            elif k=='summary': cur['msg'] = v
    return res

# %% ../nbs/01_repo.ipynb #0a84bdeb
@patch
def trace(self:Repo, path, *args, func=None, lines=None, regex=None, **kwargs):
    "Trace the evolution of a range of `path` (`git log -L`): `Commits` newest first, each with its `.patch`"
    spec = _lspec(func, lines, regex)
    if not spec: raise TypeError('trace needs one of func, lines, or regex')
    res = self('log', f'-L{spec}:{path}', *args, format='%x1e'+'%x1f'.join(_commit_f.values()), mute_errors=True, **kwargs)
    out = Commits()
    for rec in (res or '').split('\x1e'):
        if not rec.strip(): continue
        head,_,patch = rec.partition('\n')
        out.append(Commit({k:_conv(k,v) for k,v in zip(_commit_f, head.split('\x1f'))}, _g=self, patch=patch.strip('\n')))
    return out

# %% ../nbs/01_repo.ipynb #80c49ba3
class Remote(GitObj):
    "A configured remote"
    def __repr__(self): return f'{self.name}\t{self.url}'

class Remotes(L):
    "Remotes shown as `git remote -v`-style lines"
    def __repr__(self): return '\n'.join(repr(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

@patch(as_prop=True)
def remotes(self:Repo):
    "Configured remotes as `Remotes`"
    res = {}
    for ln in (self('remote', '-v', mute_errors=True) or '').splitlines():
        nm,rest = ln.split('\t')
        res.setdefault(nm, Remote(name=nm, url=rest.split()[0], _g=self))
    return Remotes(res.values())

# %% ../nbs/01_repo.ipynb #c19ceaa8
@patch
def fetch(self:Repo, *args, **kwargs):
    "Fetch, returning the local `branches` with refreshed tracking info"
    self('fetch', *args, **kwargs)
    return self.branches

@patch
def push(self:Repo, *args, **kwargs):
    "Push, returning the current branch's refreshed `Ref`"
    self('push', *args, **kwargs)
    return first(o for o in self.branches if o.cur=='*')

# %% ../nbs/01_repo.ipynb #bc13efa5
@patch(cls_method=True)
def clone(cls:Repo, url, path=None, **kwargs):
    "Clone `url` into `path` (default: the repo's name in the cwd), returning a `Repo` on the checkout"
    if path is None: path = re.sub(r'\.git$', '', str(url).rstrip('/').split('/')[-1])
    path = Path(path)
    Git(path.parent)('clone', str(url), path.name, **kwargs)
    return cls(path)

# %% ../nbs/01_repo.ipynb #6cc1ce2c
_stash_f = dict(_commit_f, sel='%gd')

class Stash(Commit):
    "A stash entry: a real commit addressed `stash@{n}`"
    def __repr__(self): return f'{self.sel}: {self.msg}'

class Stashes(L):
    "Stash entries shown as `stash list`-style lines"
    def __repr__(self): return '\n'.join(repr(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

@patch(as_prop=True)
def stashes(self:Repo):
    "Stash entries, newest first"
    res = self('stash', 'list', format=_fmt(_stash_f), mute_errors=True)
    return Stashes(Stash(d, _g=self) for d in _parse(_stash_f, res))

@patch
def stash(self:Repo, msg=None, **kwargs):
    "Stash worktree changes, returning the resulting `Status`"
    if msg: kwargs['m'] = msg
    self('stash', 'push', mute_errors=True, **kwargs)
    return self.status

@patch
def pop(self:Stash, **kwargs):
    "Re-apply and drop this stash, returning the resulting `Status`"
    self._g('stash', 'pop', self.sel, mute_errors=True, **kwargs)
    return self._g.status

@patch
def drop(self:Stash, **kwargs):
    "Delete this stash, returning the resulting `Status`"
    self._g('stash', 'drop', self.sel, mute_errors=True, **kwargs)
    return self._g.status
